[project]
name = "avogadro-rdkit"
version = "0.2.1"
description = "RDKit-based plugins for Avogadro 2"
authors = [{name = "Geoff Hutchison", email = "geoff.hutchison@gmail.com"}]
license = "BSD-3-Clause"
requires-python = ">=3.11"
dependencies = ["rdkit>=2023.3.2"]

[project.scripts]
avogadro-rdkit = "avogadro_rdkit:main"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.avogadro]
minimum-avogadro-version = "1.103"

[[tool.avogadro.menu-commands]]
identifier = "standardize"
input-format = "sdf"
menu = "Extensions"
submenu = "RDKit"
item = "Standardize"
menu-priorities = [ 900, 750 ]

[[tool.avogadro.menu-commands]]
identifier = "tautomer"
input-format = "sdf"
menu = "Extensions"
submenu = "RDKit"
item = "Canonical Tautomer"
menu-priorities = [ 900, 700 ]

[[tool.avogadro.menu-commands]]
identifier = "mmff94"
input-format = "sdf"
menu = "Extensions"
submenu = "RDKit"
item = "MMFF94 Optimize"
menu-priorities = [ 900, 550 ]

[[tool.avogadro.menu-commands]]
identifier = "uff"
input-format = "sdf"
menu = "Extensions"
submenu = "RDKit"
item = "UFF Optimize"
menu-priorities = [ 900, 540 ]

[[tool.avogadro.menu-commands]]
identifier = "etkdg"
input-format = "sdf"
user-options = "customization/etkdg_options.json"
menu = "Extensions"
submenu = "RDKit"
item = "ETKDG Conformer…"
menu-priorities = [ 900, 530 ]

[[tool.avogadro.menu-commands]]
identifier = "assign-stereo"
input-format = "sdf"
input-cjson = true
menu = "Extensions"
submenu = "RDKit"
item = "Assign Stereochemistry"
menu-priorities = [ 900, 300 ]

[[tool.avogadro.menu-commands]]
identifier = "select-smarts"
input-format = "sdf"
user-options = "customization/smarts_options.json"
menu = "Select"
item = "Select by SMARTS…"
menu-priorities = [ 500 ]

[[tool.avogadro.menu-commands]]
identifier = "insert-smiles"
input-format = "sdf"
user-options = "customization/smiles_options.json"
menu = "Build"
submenu = "Insert"
item = "SMILES (RDKit)…"
menu-priorities = [ 500 ]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
avogadro-rdkit = { path = ".", editable = true }

[tool.pixi.tasks]
